# Generated by Django 3.0.4 on 2020-04-02 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, max_length=10)),
                ('feature', models.IntegerField(blank=True)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('document', models.CharField(blank=True, max_length=50)),
                ('countries', models.ManyToManyField(related_name='countries', to='catalog.Country')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='catalog.Country')),
                ('not_countries', models.ManyToManyField(related_name='not_countries', to='catalog.Country')),
                ('not_country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='not_country', to='catalog.Country')),
                ('p_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.PaymentsCode')),
                ('p_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.PaymentsType')),
            ],
        ),
    ]
