# Generated by Django 3.0.4 on 2020-04-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytype',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='countries', to='catalog.Country'),
        ),
        migrations.AlterField(
            model_name='paytype',
            name='not_countries',
            field=models.ManyToManyField(blank=True, related_name='not_countries', to='catalog.Country'),
        ),
    ]
