# Generated by Django 3.0.4 on 2020-04-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200403_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytype',
            name='feature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
