# Generated by Django 3.0.4 on 2020-04-02 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200403_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytype',
            name='countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='countries', to='catalog.Country'),
        ),
        migrations.AlterField(
            model_name='paytype',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='catalog.Country'),
        ),
        migrations.AlterField(
            model_name='paytype',
            name='not_countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='not_countries', to='catalog.Country'),
        ),
        migrations.AlterField(
            model_name='paytype',
            name='not_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='not_country', to='catalog.Country'),
        ),
    ]
